services:
    app:
        build: ./docker/nginx
        container_name: app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.0.39
        container_name: db
        environment:
            AllowEmptyPassword: "false"
            MYSQL_ROOT_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "13306:3306"
        networks:
            - laravel


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        networks:
            - laravel
networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
